##
# @author Alexander Breuer (alex.breuer AT uni-jena.de)
#
# @section DESCRIPTION
# Collects sources for a build.
##
Import("env")

remarks_flags = []
if "remarks" in env["mode"]:
    remarks_flags = ["-Rpass=.*", "-Rpass-missed=.*", "-Rpass-analysis=.*"]

# gather sources
l_sources = [
    "io/Csv.cpp",
    "io/NetCDF.cpp",
    "io/Stations.cpp",
    "patches/WavePropagation1d.cpp",
    "patches/WavePropagation2d.cpp",
    "setups/ArtificialTsunami2d.cpp",
    "setups/DamBreak1d.cpp",
    "setups/DamBreak2d.cpp",
    "setups/RareRare1d.cpp",
    "setups/Reservoir1d.cpp",
    "setups/ShockShock1d.cpp",
    "setups/SubCritical1d.cpp",
    "setups/SuperCritical1d.cpp",
    "setups/TsunamiEvent1d.cpp",
    "setups/TsunamiEvent2d.cpp",
    "solvers/FWave.cpp",
    "solvers/Roe.cpp",
]

for l_so in l_sources:
    env.sources.append(env.Object(l_so, CXXFLAGS=env["CXXFLAGS"] + remarks_flags))

env.standalone = env.Object("main.cpp", CXXFLAGS=env["CXXFLAGS"] + remarks_flags)

# gather unit tests
l_tests = [
    "io/Csv.test.cpp",
    "io/NetCDF.test.cpp",
    "patches/WavePropagation1d.test.cpp",
    "setups/DamBreak1d.test.cpp",
    "setups/RareRare1d.test.cpp",
    "setups/ShockShock1d.test.cpp",
    "solvers/FWave.test.cpp",
    "solvers/Roe.test.cpp",
    "tests.cpp",
]

for l_te in l_tests:
    env.tests.append(env.Object(l_te))

Export("env")
