name: Tsunami Lab
on: [push, pull_request]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: dependencies
        run: |
          sudo apt-get update
          sudo apt-get install scons valgrind cppcheck
          git submodule update --init --recursive

      - name: cppcheck
        run: cppcheck src/ --template=gcc --force --error-exitcode=1

      - name: sanitize
        run: |
          scons mode=debug+san
          ./build/tests
          ./build/tsunami_lab 5000
          scons mode=release+san
          ./build/tests
          ./build/tsunami_lab 50000

      - name: valgrind
        run: |
          scons mode=debug
          valgrind ./build/tests
          valgrind ./build/tsunami_lab 5000
